-- Password is ****** so don't even try
--statement-- 
INSERT INTO customers (given_name, fullname, email, password, local) VALUES ('Johnny', 'Johnny Utah', 'demo@sumanb.com', '$2a$10$YHttx140b7bwH2ICO4X2fOn03cQagPTWX/iCa7FvzjJMgDbqOYso2', TRUE);
--statement-- 
INSERT INTO os (name)
  VALUES ('Mac OS X'), ('Chrome OS'), ('Windows 10'), ('Windows 8.1'), ('Windows 7 Home');
--statement-- 
INSERT INTO processor (name)
  VALUES ('Intel Core i7'), ('Intel Core i5'), ('Intel Core i3'), ('Intel Core 2'), ('AMD');
--statement-- 
INSERT INTO brand (name)
  VALUES ('Apple'), ('Microsoft'), ('HP'), ('Dell'), ('Asus'), ('Acer'), ('Samsung'), ('Lenovo'), ('Toshiba');
--statement-- 
INSERT INTO storage_type (name)
  VALUES ('SSD'), ('Hard Disk');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('HP Stream 13.3-Inch Laptop (Intel Celeron, 2 GB RAM, 32 GB SSD, Cobalt Blue) with Office 365 Personal for One Year', 5, 4, 3, 'https://images-na.ssl-images-amazon.com/images/I/41C3APhWhbL._AC_US200_.jpg', 2, 1, 32, 1.7, 239.99, 'https://images-na.ssl-images-amazon.com/images/I/41C3APhWhbL._AC_US500_.jpg', '{"2.0GHz AMD Quad-Core A6-5200 APU (2MB L2 Cache), AMD Radeon R4 graphics with up to 2048MB total graphics memory","4GB DDR3 SDRAM (1 DIMM) Memory, 500GB 5400RPM hard drive, SuperMulti DVD Burner","15.6-inch diagonal HD BrightView WLED-backlit display (1366x768)","802.11b/g/n WLAN, Integrated 10/100 BASE-T Ethernet LAN, HD Webcam, Multi-Format Digital Media Card Reader, 1 SuperSpeed USB 3.0, 2USB 2.0, HDMI, RJ-45, Headphone, Microphone, DTS Studio Sound with dual speakers, Full-size keyboard with numeric keypad, Front facing VGA Webcam with integrated digital microphone","Windows 10 Home 64 Bit, 3-cell 31WHr 2.8Ah lithium-ion polymer battery, Black"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Samsung Chromebook 3 XE500C13-K02US 4 GB RAM 11.6" Laptop (Black)', 2, 4, 7, 'https://images-na.ssl-images-amazon.com/images/I/4112yZZu8PL._AC_US200_.jpg', 4, 1, 16, 3, 287.99, 'https://images-na.ssl-images-amazon.com/images/I/4112yZZu8PL.jpg', '{"Intel Celeron N3160 Quad-Core Processor 1.6GHz (Up to 2.24GHz)","100% Aluminum Chassis","4GB LPDDR3 Onboard SDRAM Memory, 32GB Internal Storage","14'' Full HD IPS Display (1920 x 1080), Intel HD Graphics","Google Chrome, Up to 12-hours Battery Life"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS ZenBook Flip UX360CA-DBM1T 13.3-inch Touchscreen Laptop (Intel Core M CPU, 8 GB RAM, 512 GB Solid State Drive, Windows 10)', 3, 4, 5, 'https://images-na.ssl-images-amazon.com/images/I/31-49dCBMwL._AC_US200_.jpg', 8, 1, 512, 3.5, 679, 'https://images-na.ssl-images-amazon.com/images/I/31-49dCBMwL._AC_US500_.jpg', '{"13.3'' Touch IPS 4K Ultra­-HD display, 3840 x 2160 resolution","Powerful Intel Skylake Core i7­-6700HQ 2.6 GHz Quad­core CPU (turbo to 3.5GHz). Nvidia GTX960M GPU","512GB SSD with transfer speeds of 1400MB/s and 16GB DDR4 RAM","1x Thunderbolt III (via USB Type­C), 1x Gen 2 USB 3.1 Type­C, 3x USB 3.0, 1x HDMI.Bluetooth 4.0, SDXC reader, 802.11ac Wi­Fi","Windows 10 (64 bit) Signature Edition. 1 ­year International Warranty with 1­ year Accidental Damage Protection."}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS VivoBook E403SA-US21 14-inch Full HD Laptop (Intel Quad-Core N3700 Processor, 4 GB DDR3 RAM, 128GB eMMC Storage, Windows 10 Home OS) Metallic Gray', 4, 2, 5, 'https://images-na.ssl-images-amazon.com/images/I/51Ip+mFaQTL._AC_US200_.jpg', 8, 1, 128, 3.4, 379, 'https://images-na.ssl-images-amazon.com/images/I/51Ip+mFaQTL._AC_US500_.jpg', '{"14-Inch Full HD 1080P Display, Windows 10 Signature Edition Pre-Installed","Intel Braswell Quad Core N3700 1.6 GHz, Turbo to 2.4 GHz","Ultra-thin and light design: 0.7'' thin and 3.3 lbs. light. All-day battery rated 57 Whrs","128GB eMMC Flash and 4GB RAM for fast boot time and application performance","Wi-Fi 802. 11 AC. Bluetooth 4.0. 1x USB 2.0, 1x USB 3.0, 1x USB3.1 Type C, 1 x HDMI. One year Domestic Warranty."}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('2016 Newest Dell Inspiron 5000 Touchscreen 15.6" FHD Laptop, 6th Intel Core i5-6200U up to 2.8GHz, 8 GB RAM, 1 TB HDD, DVD, Backlit keyboard, HDMI, Bluetooth, 802.11ac, RealSense 3D Webcam, Windows 10', 3, 1, 4, 'https://images-na.ssl-images-amazon.com/images/I/41TEYABuTVL._AC_US200_.jpg', 8, 1, 1024, 4, 749.99, 'https://images-na.ssl-images-amazon.com/images/I/41TEYABuTVL._AC_US500_.jpg', '{"15.6 in Full HD LED-backlit touchscreen with Truelife (1920 x 1080), 10-finger multi-touch support, Intel HD Graphics 520 with shared graphics memory","6th Generation Intel Core i5-6200U Dual-Core Processor 2.3 GHz (max boost speed up to 2.8GHz) 4MB L3 Cache, 8GB DDR3L 1600 MHz, 1TB 5400 RPM HDD","DVD +/- RW, SD card reader, Waves MaxxAudio Pro, Intel RealSense 3D camera, Backlit keyboard","802.11ac/a/b/g/n (Miracast enabled) wireless; Bluetooth 4.0; 1X USB 3.0 2X USB 2.0; HDMI 1.4; Headphone output/Microphone input combo • LAN (10/100)","Windows 10 Home, 64-bit, 4-cell lithium-ion battery, Silver"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('HP Pavilion 13-s128nr x360 13.3-Inch Full-HD 2-in-1 Laptop (Core i5, 16GB RAM, 128GB SSD) with Windows 10', 3, 2, 3, 'https://images-na.ssl-images-amazon.com/images/I/41AuBloBZSL._AC_US200_.jpg', 16, 1, 128, 3.3, 1199, 'https://images-na.ssl-images-amazon.com/images/I/41AuBloBZSL._AC_US500_.jpg', '{"2.0GHz Intel Quad-Core A6-5200 APU (2MB L2 Cache), AMD Radeon R4 graphics with up to 2048MB total graphics memory","4GB DDR3 SDRAM (1 DIMM) Memory, 500GB 5400RPM hard drive, SuperMulti DVD Burner","15.6-inch diagonal HD BrightView WLED-backlit display (1366x768)","802.11b/g/n WLAN, Integrated 10/100 BASE-T Ethernet LAN, HD Webcam, Multi-Format Digital Media Card Reader, 1 SuperSpeed USB 3.0, 2USB 2.0, HDMI, RJ-45, Headphone, Microphone, DTS Studio Sound with dual speakers, Full-size keyboard with numeric keypad, Front facing VGA Webcam with integrated digital microphone","Windows 10 Home 64 Bit, 3-cell 31WHr 2.8Ah lithium-ion polymer battery, Black"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Lenovo ideapad 300 80Q70021US 15.6-Inch Laptop (Intel Core i5 6200U, 8 GB RAM, 1TB HDD, Windows 10)', 3, 2, 8, 'https://images-na.ssl-images-amazon.com/images/I/41iHVbXjEWL._AC_US200_.jpg', 8, 2, 1024, 1.5, 1099.99, 'https://images-na.ssl-images-amazon.com/images/I/41iHVbXjEWL._AC_US500_.jpg', '{"Intel Core i5-4300U (Dual Core, 1.9 / 2.9GHz, 3MB, 1600MHz)","8GB Upgraded DDR3 Memory(maximum memory capacity 16 GB), 500 GB 7200rpm HDD","14 Inch HD (1366x768) with HD Graphics 4400","Intel 7265 ac WIFI + BlueTooth 4.0 , Fingerprint Reader","Windows 7 Professional Installed with Licence Upgradable to Windows 8.1 Professional"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Dell Inspiron i7359-8404SLV 13.3 Inch 2-in-1 Touchscreen Laptop (6th Generation Intel Core i7, 8 GB RAM, 256 GB SSD)', 4, 2, 4, 'https://images-na.ssl-images-amazon.com/images/I/410b5opN3EL._AC_US200_.jpg', 8, 1, 256, 2.5, 1299, 'https://images-na.ssl-images-amazon.com/images/I/410b5opN3EL._AC_US500_.jpg', '{"Intel Quad Core i7-6700HQ 2.6 GHz Processor; NVIDIA GeForce GTX 960M 4GB GDDR5","8 GB DDR3L SDRAM","1 TB HDD + 8 GB SSD Hybrid Drive Storage; Optical Drive Not included","15.6 Inch FHD (1920 x 1080 pixels) LED-lit Truelife Screen","Windows 10 Operating System; Matte Black featuring Red Chassis"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS K501UX 15.6-inch Gaming Laptop (Intel Core i7 Processor, 8GB RAM, 256GB SSD Hard Drive, Windows 10 (64 bit)), Black/Silver Metal', 4, 1, 5, 'https://images-na.ssl-images-amazon.com/images/I/41WN8y6bohL._AC_US200_.jpg', 8, 1, 256, 4, 199.99, 'https://images-na.ssl-images-amazon.com/images/I/41WN8y6bohL._AC_US500_.jpg', '{"Powerful 6th-generation Intel Core i7-6500U 2.5GHz (Turbo up to 3.1GHz). Skylake","15.6 inches Matte FHD display. 1920 by 1080 resolution. Windows 10 Operating System.","NVIDIA GeForce GTX 960M gaming graphic card; 8GB RAM; 512GB SSD Storage. Backlit keyboard.","Gigabit Dual-Band 802.11AC ultra-fast Wi-Fi.","2x USB 2.0, 2x USB 3.0, 1x Headphone-out & Audio-in Combo Jack, 1x RJ45 LAN Jack for LAN insert, 1x HDMI, 1x Card Reader"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS Chromebook Flip 10.1-Inch Convertible 2 in 1 Touchscreen (Rockchip, 4 GB, 16GB SSD, Silver)', 2, 5, 5, 'https://images-na.ssl-images-amazon.com/images/I/41MW-Z2bY6L._AC_US200_.jpg', 4, 1, 16, 2.4, 349.99, 'https://images-na.ssl-images-amazon.com/images/I/41MW-Z2bY6L._AC_US500_.jpg', '{"Intel Bay Trail-M N2840 Dual-Core 2.16GHz (Turbo up to 2.58GHz) 2 GB","4GB DDR3L (1600MHz) on board and 16G EMMC","11.6 Inch 1366x768 LED screen","Equipped Trusted Platform Module(TPM)","Up to 10hrs battery life. 1 year International Warranty with 1 year Accidental Damage Protection"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Apple 13-inch MacBook Pro (Intel Dual Core i5 2.5GHz, 4GB RAM, 500GB HDD, HD Graphics 4000, OS X Lion)', 1, 2, 1, 'https://images-na.ssl-images-amazon.com/images/I/510z0ixPJGL._AC_US200_.jpg', 4, 2, 500, 4, 999.99, 'https://images-na.ssl-images-amazon.com/images/I/510z0ixPJGL._AC_US500_.jpg', '{"2.7 GHz Intel Core i5 (Broadwell)8GB of Onboard 1866 MHz LPDDR3 RAM","128GB PCIe-Based Flash StorageIntegrated Intel Iris Graphics 6100","13.3'' LED-Backlit IPS Retina Display2560 x 1600 Native Resolution","802.11a/b/g/n/ac Wi-Fi, Bluetooth 4.0Thunderbolt 2, USB 3.0, HDMI","Force Touch TrackpadMac OS X 10.10 or 10.11","Non-Removable Lithium-Polymer Providing up to 10 Hours per Charge"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Microsoft Surface Book (512 GB, 16 GB RAM, Intel Core i7, NVIDIA GeForce graphics)', 3, 1, 2, 'https://images-na.ssl-images-amazon.com/images/I/419JhZ2ylwL._AC_US200_.jpg', 16, 1, 512, 4, 1699, 'https://images-na.ssl-images-amazon.com/images/I/419JhZ2ylwL._AC_US500_.jpg', '{"13.5-inch PixelSense touchscreen display (3000 x 2000) resolution","Windows 10 Pro operating system","Incredibly mobile at 3.48 pounds (1576 grams)","Surface Pen included","Please refer User Guide before use."}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Acer Chromebook CB3-131-C3SZ 11.6-Inch Laptop (Intel Celeron N2840 Dual-Core Processor,2 GB RAM,16 GB Solid State Drive,Chrome), White', 2, 4, 6, 'https://images-na.ssl-images-amazon.com/images/I/51-19G04kHL._AC_US200_.jpg', 2, 1, 16, 3.4, 397.99, 'https://images-na.ssl-images-amazon.com/images/I/51-19G04kHL._AC_US500_.jpg', '{"Intel Celeron N3160 Quad-Core Processor 1.6GHz (Up to 2.24GHz)","100% Aluminum Chassis","4GB LPDDR3 Onboard SDRAM Memory, 32GB Internal Storage","14'' Full HD IPS Display (1920 x 1080), Intel HD Graphics","Google Chrome, Up to 12-hours Battery Life"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('HP 15-ay018nr 15.6-Inch Laptop (Intel Core i7, 8GB RAM, 256GB SSD)', 5, 1, 3, 'https://images-na.ssl-images-amazon.com/images/I/41+teQlrUsL._AC_US200_.jpg', 8, 1, 256, 3.4, 250, 'https://images-na.ssl-images-amazon.com/images/I/41+teQlrUsL._AC_US500_.jpg', '{"Intel Core i5-6200U, 2.3GHz, Dual-Core Processor","8GB DDR3L SDRAM Memory","More productive. Windows 10 is the best for bringing ideas forward and getting things done.","128GB Solid-State Drive, No Optical Drive","13.3'' diagonal FHD IPS WLED-backlit touch screen (1920x1080)"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Acer Chromebook 15 CB5-571-C1DZ (15.6-Inch Full HD IPS, 4GB RAM, 16GB SSD)', 2, 4, 6, 'https://images-na.ssl-images-amazon.com/images/I/5165f4fk49L._AC_US200_.jpg', 4, 1, 16, 2.2, 250, 'https://images-na.ssl-images-amazon.com/images/I/5165f4fk49L._AC_US500_.jpg', '{"Intel Celeron N3160 Quad-Core Processor 1.6GHz (Up to 2.24GHz)","100% Aluminum Chassis","4GB LPDDR3 Onboard SDRAM Memory, 32GB Internal Storage","14'' Full HD IPS Display (1920 x 1080), Intel HD Graphics","Google Chrome, Up to 12-hours Battery Life"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Apple Macbook Pro MJLQ2LL/A 15-inch Laptop (2.2 GHz Intel Core i7 Processor, 16GB RAM, 256 GB Hard Drive, Mac OS X)', 1, 1, 1, 'https://images-na.ssl-images-amazon.com/images/I/41nOwxSNxpL._AC_US200_.jpg', 16, 1, 128, 4.9, 1699, 'https://images-na.ssl-images-amazon.com/images/I/41nOwxSNxpL._AC_US500_.jpg', '{"2.7 GHz Intel Core i5 (Broadwell)8GB of Onboard 1866 MHz LPDDR3 RAM","128GB PCIe-Based Flash StorageIntegrated Intel Iris Graphics 6100","13.3'' LED-Backlit IPS Retina Display2560 x 1600 Native Resolution","802.11a/b/g/n/ac Wi-Fi, Bluetooth 4.0Thunderbolt 2, USB 3.0, HDMI","Force Touch TrackpadMac OS X 10.10 or 10.11","Non-Removable Lithium-Polymer Providing up to 10 Hours per Charge"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Apple MMGF2LL/A MacBook Air 13.3-Inch Laptop (128 GB) NEWEST VERSION', 1, 2, 1, 'https://images-na.ssl-images-amazon.com/images/I/41AerRC5u6L._AC_US200_.jpg', 4, 1, 128, 4.5, 994, 'https://images-na.ssl-images-amazon.com/images/I/41AerRC5u6L._AC_US500_.jpg', '{"1.6 GHz dual-core Intel Core i5 (Turbo Boost up to 2.7 GHz) with 3 MB shared L3 cache","8 GB of 1600 MHz LPDDR3 RAM; 256 GB PCIe-based flash storage","13.3-Inch (diagonal) LED-backlit Glossy Widescreen Display, 1440 x 900 resolution","Intel HD Graphics 6000","OS X El Capitan, Up to 12 Hours of Battery Life","Macbook Air does not have a Retina display on any model."}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Apple MacBook Pro MF840LL/A 13.3-Inch Laptop with Retina Display (256 GB, 2.7 GHz dual-core Intel Core i5 processor, 8 GB 1866 MHz LPDDR3 RAM), Silver', 1, 2, 1, 'https://images-na.ssl-images-amazon.com/images/I/51nHbuhKnqL._AC_US200_.jpg', 8, 1, 256, 4.2, 1099.99, 'https://images-na.ssl-images-amazon.com/images/I/51nHbuhKnqL._AC_US500_.jpg', '{"2.7 GHz Intel Core i5 (Broadwell)8GB of Onboard 1866 MHz LPDDR3 RAM","128GB PCIe-Based Flash StorageIntegrated Intel Iris Graphics 6100","13.3'' LED-Backlit IPS Retina Display2560 x 1600 Native Resolution","802.11a/b/g/n/ac Wi-Fi, Bluetooth 4.0Thunderbolt 2, USB 3.0, HDMI","Force Touch TrackpadMac OS X 10.10 or 10.11","Non-Removable Lithium-Polymer Providing up to 10 Hours per Charge"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS C200MA Chromebook 11.6 Inch, Intel Dual Core, 4GB RAM, 16G EMMC + TPM (Black)', 2, 4, 5, 'https://images-na.ssl-images-amazon.com/images/I/41FNGl9uX1L._AC_US200_.jpg', 4, 1, 16, 3.8, 199.99, 'https://images-na.ssl-images-amazon.com/images/I/41FNGl9uX1L._AC_US500_.jpg', '{"Intel Bay Trail-M N2840 Dual-Core 2.16GHz (Turbo up to 2.58GHz) 2 GB","4GB DDR3L (1600MHz) on board and 16G EMMC","11.6 Inch 1366x768 LED screen","Equipped Trusted Platform Module(TPM)","Up to 10hrs battery life. 1 year International Warranty with 1 year Accidental Damage Protection"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS C201 11.6 Inch Chromebook (Rockchip, 4 GB, 16GB SSD, Navy Blue)', 2, 5, 5, 'https://images-na.ssl-images-amazon.com/images/I/41yFEX+AEQL._AC_US200_.jpg', 4, 1, 16, 3.2, 245, 'https://images-na.ssl-images-amazon.com/images/I/41yFEX+AEQL._AC_US500_.jpg', '{"Intel Bay Trail-M N2840 Dual-Core 2.16GHz (Turbo up to 2.58GHz) 2 GB","4GB DDR3L (1600MHz) on board and 16G EMMC","11.6 Inch 1366x768 LED screen","Equipped Trusted Platform Module(TPM)","Up to 10hrs battery life. 1 year International Warranty with 1 year Accidental Damage Protection"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Acer Chromebook 14, Aluminum, 14-inch Full HD, Intel Celeron Quad-Core N3160, 4GB LPDDR3, 32GB, Chrome, CB3-431-C5FM', 2, 4, 6, 'https://images-na.ssl-images-amazon.com/images/I/518PvURfFsL._AC_US200_.jpg', 4, 1, 256, 3.5, 279, 'https://images-na.ssl-images-amazon.com/images/I/518PvURfFsL._AC_US500_.jpg', '{"Intel Celeron N3160 Quad-Core Processor 1.6GHz (Up to 2.24GHz)","100% Aluminum Chassis","4GB LPDDR3 Onboard SDRAM Memory, 32GB Internal Storage","14'' Full HD IPS Display (1920 x 1080), Intel HD Graphics","Google Chrome, Up to 12-hours Battery Life"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Acer Aspire E 15, 15.6 Full HD, Intel Core i7, NVIDIA 940MX, 8GB DDR4, 256GB SSD, Windows 10 Home, E5-575G-76YK', 5, 1, 6, 'https://images-na.ssl-images-amazon.com/images/I/41BrD2bCAeL._AC_US200_.jpg', 8, 1, 128, 3.7, 549.99, 'https://images-na.ssl-images-amazon.com/images/I/41BrD2bCAeL._AC_US500_.jpg', '{"6th Generation Intel Core i5-6200U Processor (Up to 2.8GHz)","15.6-inch Full HD Display, NVIDIA GeForce 940MX with 2GB DDR5 VRAM","8GB DDR4 Memory, 256GB SSD","Windows 10 Home; Backlit Keyboard","Up to 12-hours Battery Life; 6-cell Li-Ion (2800 mAh) Battery"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('New Apple MMGF2LL/A MacBook Air 13.3-Inch Laptop (8GB RAM 128 GB SSD) MMGF2 NEWEST VERSION', 1, 2, 1, 'https://images-na.ssl-images-amazon.com/images/I/516KpKhNFPL._AC_US200_.jpg', 8, 1, 128, 4.3, 999.99, 'https://images-na.ssl-images-amazon.com/images/I/516KpKhNFPL._AC_US500_.jpg', '{"1.6 GHz dual-core Intel Core i5 (Turbo Boost up to 2.7 GHz) with 3 MB shared L3 cache","8 GB of 1600 MHz LPDDR3 RAM; 256 GB PCIe-based flash storage","13.3-Inch (diagonal) LED-backlit Glossy Widescreen Display, 1440 x 900 resolution","Intel HD Graphics 6000","OS X El Capitan, Up to 12 Hours of Battery Life","Macbook Air does not have a Retina display on any model."}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS ROG GL552VW-DH71 15-Inch Gaming Laptop, Discrete GPU GeForce GTX 960M 2GB VRAM, 32GB DDR4, 1TB (ROG Metallic)', 3, 1, 5, 'https://images-na.ssl-images-amazon.com/images/I/51rDLb7i7RL._AC_US200_.jpg', 32, 2, 128, 4.6, 1699, 'https://images-na.ssl-images-amazon.com/images/I/51rDLb7i7RL._AC_US500_.jpg', '{"Powerful 6th-generation Intel Core i7-6500U 2.5GHz (Turbo up to 3.1GHz). Skylake","15.6 inches Matte FHD display. 1920 by 1080 resolution. Windows 10 Operating System.","NVIDIA GeForce GTX 960M gaming graphic card; 8GB RAM; 512GB SSD Storage. Backlit keyboard.","Gigabit Dual-Band 802.11AC ultra-fast Wi-Fi.","2x USB 2.0, 2x USB 3.0, 1x Headphone-out & Audio-in Combo Jack, 1x RJ45 LAN Jack for LAN insert, 1x HDMI, 1x Card Reader"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Apple MacBook Air MJVM2LL/A 11.6-Inch laptop(1.6 GHz Intel i5, 128 GB SSD, Integrated Intel HD Graphics 6000, Mac OS X Yosemite)', 1, 2, 1, 'https://images-na.ssl-images-amazon.com/images/I/51a7lDlQ9HL._AC_US200_.jpg', 4, 1, 128, 2.1, 845, 'https://images-na.ssl-images-amazon.com/images/I/51a7lDlQ9HL._AC_US500_.jpg', '{"1.6 GHz dual-core Intel Core i5 (Turbo Boost up to 2.7 GHz) with 3 MB shared L3 cache","8 GB of 1600 MHz LPDDR3 RAM; 256 GB PCIe-based flash storage","13.3-Inch (diagonal) LED-backlit Glossy Widescreen Display, 1440 x 900 resolution","Intel HD Graphics 6000","OS X El Capitan, Up to 12 Hours of Battery Life","Macbook Air does not have a Retina display on any model."}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Apple MMGG2LL/A MacBook Air 13.3-Inch Laptop (Intel Core i5, 8GB, 256GB,Mac OS X), Silver', 1, 2, 1, 'https://images-na.ssl-images-amazon.com/images/I/51a7lDlQ9HL._AC_US200_.jpg', 8, 1, 256, 4.6, 1299, 'https://images-na.ssl-images-amazon.com/images/I/51a7lDlQ9HL._AC_US500_.jpg', '{"1.6 GHz dual-core Intel Core i5 (Turbo Boost up to 2.7 GHz) with 3 MB shared L3 cache","8 GB of 1600 MHz LPDDR3 RAM; 256 GB PCIe-based flash storage","13.3-Inch (diagonal) LED-backlit Glossy Widescreen Display, 1440 x 900 resolution","Intel HD Graphics 6000","OS X El Capitan, Up to 12 Hours of Battery Life","Macbook Air does not have a Retina display on any model."}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS ZenBook UX303UB 13.3-Inch QHD+ Touchscreen Laptop, Intel Core i7, 12 GB RAM, 512 GB SSD, Discrete GPU Nvidia GT940M, Windows 10 (64 bit)', 3, 1, 5, 'https://images-na.ssl-images-amazon.com/images/I/41+Ke3rTWGL._AC_US200_.jpg', 12, 1, 512, 2.9, 1499.99, 'https://images-na.ssl-images-amazon.com/images/I/41+Ke3rTWGL._AC_US500_.jpg', '{"15.6'' Touch IPS 4K Ultra­-HD display, 3840 x 2160 resolution","Powerful Intel Skylake Core i7­-6700HQ 2.6 GHz Quad­core CPU (turbo to 3.5GHz). Nvidia GTX960M GPU","512GB SSD with transfer speeds of 1400MB/s and 16GB DDR4 RAM","1x Thunderbolt III (via USB Type­C), 1x Gen 2 USB 3.1 Type­C, 3x USB 3.0, 1x HDMI.Bluetooth 4.0, SDXC reader, 802.11ac Wi­Fi","Windows 10 (64 bit) Signature Edition. 1 ­year International Warranty with 1­ year Accidental Damage Protection."}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS ZenBook Pro UX501VW 15" 4K Touchscreen Laptop (Core i7-6700HQ CPU, 16 GB DDR4, 512 GB NVMe SSD, GTX960M GPU, Thunderbolt III, Win 10 Cortana Premium)', 4, 1, 5, 'https://images-na.ssl-images-amazon.com/images/I/41oX-+X+HIL._AC_US200_.jpg', 16, 1, 512, 4.1, 1099.99, 'https://images-na.ssl-images-amazon.com/images/I/41oX-+X+HIL._AC_US500_.jpg', '{"15.6'' Touch IPS 4K Ultra­-HD display, 3840 x 2160 resolution","Powerful Intel Skylake Core i7­-6700HQ 2.6 GHz Quad­core CPU (turbo to 3.5GHz). Nvidia GTX960M GPU","512GB SSD with transfer speeds of 1400MB/s and 16GB DDR4 RAM","1x Thunderbolt III (via USB Type­C), 1x Gen 2 USB 3.1 Type­C, 3x USB 3.0, 1x HDMI.Bluetooth 4.0, SDXC reader, 802.11ac Wi­Fi","Windows 10 (64 bit) Signature Edition. 1 ­year International Warranty with 1­ year Accidental Damage Protection."}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS ZenBook UX305UA 13.3-Inch Laptop (6th Generation Intel Core i5, 8GB RAM, 256 GB SSD, Windows 10), Titanium Gold', 3, 2, 5, 'https://images-na.ssl-images-amazon.com/images/I/41vZl7Pe2HL._AC_US200_.jpg', 8, 1, 256, 4, 245, 'https://images-na.ssl-images-amazon.com/images/I/41vZl7Pe2HL._AC_US500_.jpg', '{"13.3'' Touch IPS 4K Ultra­-HD display, 3840 x 2160 resolution","Powerful Intel Skylake Core i7­-6700HQ 2.6 GHz Quad­core CPU (turbo to 3.5GHz). Nvidia GTX960M GPU","512GB SSD with transfer speeds of 1400MB/s and 16GB DDR4 RAM","1x Thunderbolt III (via USB Type­C), 1x Gen 2 USB 3.1 Type­C, 3x USB 3.0, 1x HDMI.Bluetooth 4.0, SDXC reader, 802.11ac Wi­Fi","Windows 10 (64 bit) Signature Edition. 1 ­year International Warranty with 1­ year Accidental Damage Protection."}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Apple MacBook Air MJVM2LL/A 11.6-Inch laptop(1.6 GHz Intel i5, 128 GB SSD, Integrated Intel HD Graphics 6000, Mac OS X Yosemite)', 1, 2, 1, 'https://images-na.ssl-images-amazon.com/images/I/51a7lDlQ9HL._AC_US200_.jpg', 4, 1, 128, 4, 1597.99, 'https://images-na.ssl-images-amazon.com/images/I/51a7lDlQ9HL._AC_US500_.jpg', '{"1.6 GHz dual-core Intel Core i5 (Turbo Boost up to 2.7 GHz) with 3 MB shared L3 cache","8 GB of 1600 MHz LPDDR3 RAM; 256 GB PCIe-based flash storage","13.3-Inch (diagonal) LED-backlit Glossy Widescreen Display, 1440 x 900 resolution","Intel HD Graphics 6000","OS X El Capitan, Up to 12 Hours of Battery Life","Macbook Air does not have a Retina display on any model."}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Apple MacBook Pro MF841LL/A 13.3-Inch Laptop with Retina Display (512 GB)', 1, 1, 1, 'https://images-na.ssl-images-amazon.com/images/I/51nHbuhKnqL._AC_US200_.jpg', 12, 1, 512, 4, 1399.99, 'https://images-na.ssl-images-amazon.com/images/I/51nHbuhKnqL._AC_US500_.jpg', '{"2.7 GHz Intel Core i5 (Broadwell)8GB of Onboard 1866 MHz LPDDR3 RAM","128GB PCIe-Based Flash StorageIntegrated Intel Iris Graphics 6100","13.3'' LED-Backlit IPS Retina Display2560 x 1600 Native Resolution","802.11a/b/g/n/ac Wi-Fi, Bluetooth 4.0Thunderbolt 2, USB 3.0, HDMI","Force Touch TrackpadMac OS X 10.10 or 10.11","Non-Removable Lithium-Polymer Providing up to 10 Hours per Charge"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Apple MacBook Pro MF839LL/A 13.3-Inch Laptop with Retina Display (2.7 GHz Intel Core i5 Processor, 8 GB RAM, 128 GB Hard Drive, OS X El Capitan)', 1, 2, 1, 'https://images-na.ssl-images-amazon.com/images/I/51nHbuhKnqL._AC_US200_.jpg', 8, 1, 128, 3.9, 1199, 'https://images-na.ssl-images-amazon.com/images/I/51nHbuhKnqL._AC_US500_.jpg', '{"2.7 GHz Intel Core i5 (Broadwell)8GB of Onboard 1866 MHz LPDDR3 RAM","128GB PCIe-Based Flash StorageIntegrated Intel Iris Graphics 6100","13.3'' LED-Backlit IPS Retina Display2560 x 1600 Native Resolution","802.11a/b/g/n/ac Wi-Fi, Bluetooth 4.0Thunderbolt 2, USB 3.0, HDMI","Force Touch TrackpadMac OS X 10.10 or 10.11","Non-Removable Lithium-Polymer Providing up to 10 Hours per Charge"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Dell 15.6-Inch Gaming Laptop (6th Gen Intel Quad-Core i5-6300HQ Processor up to 3.2GHz, 8GB DDR3, 256GB SSD, Nvidia GeForce GTX 960M, Windows 10)', 3, 2, 4, 'https://images-na.ssl-images-amazon.com/images/I/41XXZn8RfiL._AC_US200_.jpg', 8, 1, 256, 1.3, 779.99, 'https://images-na.ssl-images-amazon.com/images/I/810a94M0uoL._SY500_.jpg', '{"Intel Quad Core i7-6700HQ 2.6 GHz Processor; NVIDIA GeForce GTX 960M 4GB GDDR5","8 GB DDR3L SDRAM","1 TB HDD + 8 GB SSD Hybrid Drive Storage; Optical Drive Not included","15.6 Inch FHD (1920 x 1080 pixels) LED-lit Truelife Screen","Windows 10 Operating System; Matte Black featuring Red Chassis"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Apple MacBook Pro MJLT2LL/A 15.4-Inch Laptop with Retina Display (512 GB)', 1, 1, 1, 'https://images-na.ssl-images-amazon.com/images/I/41nUlN0d90L._AC_US200_.jpg', 16, 1, 512, 4.5, 1597.99, 'https://images-na.ssl-images-amazon.com/images/I/41nUlN0d90L._AC_US500_.jpg', '{"2.7 GHz Intel Core i5 (Broadwell)8GB of Onboard 1866 MHz LPDDR3 RAM","128GB PCIe-Based Flash StorageIntegrated Intel Iris Graphics 6100","13.3'' LED-Backlit IPS Retina Display2560 x 1600 Native Resolution","802.11a/b/g/n/ac Wi-Fi, Bluetooth 4.0Thunderbolt 2, USB 3.0, HDMI","Force Touch TrackpadMac OS X 10.10 or 10.11","Non-Removable Lithium-Polymer Providing up to 10 Hours per Charge"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS F555UA-EH71 15.6 Inch, Intel Core i7, 8GB, 1TB HDD Laptop, Windows 10 (64bit)', 3, 1, 5, 'https://images-na.ssl-images-amazon.com/images/I/41TwwPbHIlL._AC_US200_.jpg', 8, 2, 1024, 2.5, 1099.99, 'https://images-na.ssl-images-amazon.com/images/I/41TwwPbHIlL._AC_US500_.jpg', '{"Powerful 6th-generation Intel Core i7-6500U 2.5GHz (Turbo up to 3.1GHz). Skylake","15.6 inches Matte FHD display. 1920 by 1080 resolution. Windows 10 Operating System.","NVIDIA GeForce GTX 960M gaming graphic card; 8GB RAM; 512GB SSD Storage. Backlit keyboard.","Gigabit Dual-Band 802.11AC ultra-fast Wi-Fi.","2x USB 2.0, 2x USB 3.0, 1x Headphone-out & Audio-in Combo Jack, 1x RJ45 LAN Jack for LAN insert, 1x HDMI, 1x Card Reader"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS ROG GL552VW-DH74 15-Inch Gaming Laptop, Discrete GPU GeForce GTX 960M 4GB VRAM, 32GB DDR4, 1TB, 128GB SSD (ROG Metallic)', 4, 1, 5, 'https://images-na.ssl-images-amazon.com/images/I/41rzZTFQqWL._AC_US200_.jpg', 32, 2, 128, 4, 399.99, 'https://images-na.ssl-images-amazon.com/images/I/41rzZTFQqWL._AC_US500_.jpg', '{"Powerful 6th-generation Intel Core i7-6500U 2.5GHz (Turbo up to 3.1GHz). Skylake","15.6 inches Matte FHD display. 1920 by 1080 resolution. Windows 10 Operating System.","NVIDIA GeForce GTX 960M gaming graphic card; 8GB RAM; 512GB SSD Storage. Backlit keyboard.","Gigabit Dual-Band 802.11AC ultra-fast Wi-Fi.","2x USB 2.0, 2x USB 3.0, 1x Headphone-out & Audio-in Combo Jack, 1x RJ45 LAN Jack for LAN insert, 1x HDMI, 1x Card Reader"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS ROG G751JY-VS71(WX) 17-Inch Gaming Laptop, Nvidia GeForce GTX 980M , 64 GB RAM, 1 TB HDD (Win 10 Version)', 5, 1, 5, 'https://images-na.ssl-images-amazon.com/images/I/41HXibJZtfL._AC_US200_.jpg', 64, 2, 1024, 4, 1499.99, 'https://images-na.ssl-images-amazon.com/images/I/41HXibJZtfL._AC_US500_.jpg', '{"Powerful 6th-generation Intel Core i7-6500U 2.5GHz (Turbo up to 3.1GHz). Skylake","15.6 inches Matte FHD display. 1920 by 1080 resolution. Windows 10 Operating System.","NVIDIA GeForce GTX 960M gaming graphic card; 8GB RAM; 512GB SSD Storage. Backlit keyboard.","Gigabit Dual-Band 802.11AC ultra-fast Wi-Fi.","2x USB 2.0, 2x USB 3.0, 1x Headphone-out & Audio-in Combo Jack, 1x RJ45 LAN Jack for LAN insert, 1x HDMI, 1x Card Reader"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS F556UA-AS54 15.6-inch Full-HD Laptop (Core i5, 32GB RAM, 256GB SSD) with Windows 10, Icicle Gold', 4, 2, 5, 'https://images-na.ssl-images-amazon.com/images/I/51rDLb7i7RL._AC_US200_.jpg', 32, 1, 256, 4, 1299, 'https://images-na.ssl-images-amazon.com/images/I/51rDLb7i7RL._AC_US500_.jpg', '{"Powerful 6th-generation Intel Core i7-6500U 2.5GHz (Turbo up to 3.1GHz). Skylake","15.6 inches Matte FHD display. 1920 by 1080 resolution. Windows 10 Operating System.","NVIDIA GeForce GTX 960M gaming graphic card; 8GB RAM; 512GB SSD Storage. Backlit keyboard.","Gigabit Dual-Band 802.11AC ultra-fast Wi-Fi.","2x USB 2.0, 2x USB 3.0, 1x Headphone-out & Audio-in Combo Jack, 1x RJ45 LAN Jack for LAN insert, 1x HDMI, 1x Card Reader"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS ROG GL752VW-DH74 17-Inch Gaming Laptop, Discrete GPU GeForce GTX 960M 4 GB VRAM, 16GB DDR4, 1 TB, 128 GB SSD (ROG Metallic)', 5, 1, 5, 'https://images-na.ssl-images-amazon.com/images/I/41TRuOp12iL._AC_US200_.jpg', 4, 1, 128, 3.9, 699.99, 'https://images-na.ssl-images-amazon.com/images/I/41TRuOp12iL._AC_US500_.jpg', '{"Powerful 6th-generation Intel Core i7-6500U 2.5GHz (Turbo up to 3.1GHz). Skylake","15.6 inches Matte FHD display. 1920 by 1080 resolution. Windows 10 Operating System.","NVIDIA GeForce GTX 960M gaming graphic card; 8GB RAM; 512GB SSD Storage. Backlit keyboard.","Gigabit Dual-Band 802.11AC ultra-fast Wi-Fi.","2x USB 2.0, 2x USB 3.0, 1x Headphone-out & Audio-in Combo Jack, 1x RJ45 LAN Jack for LAN insert, 1x HDMI, 1x Card Reader"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Asus X540LA-SI30205P 15.6-Inch Laptop (Intel Core i3, 4GB Memory,1TB Hard Drive, Windows 10 Home), Silver', 3, 3, 5, 'https://images-na.ssl-images-amazon.com/images/I/51J1ndMEUQL._AC_US200_.jpg', 4, 2, 1024, 1.9, 399.99, 'https://images-na.ssl-images-amazon.com/images/I/51J1ndMEUQL._AC_US500_.jpg', '{"15.6'' display HD resolution.","5th Gen Intel CoreTM i3-5020U processor Smart dual-core, four-way processing performance for HD-quality computing","4GB system memory for basic multitasking","1TB hard drive for ample file storage space","Windows 10 Home"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('HP - 15.6" Laptop / AMD A6-Series / 4GB Memory / 500GB Hard Drive / DVDRW/CD-RW / Windows 10 - Black', 4, 3, 3, 'https://images-na.ssl-images-amazon.com/images/I/416uktsoFOL._AC_US200_.jpg', 4, 2, 32, 3, 285, 'https://images-na.ssl-images-amazon.com/images/I/416uktsoFOL._AC_US500_.jpg', '{"Intel Core i5-6200U, 2.3GHz, Dual-Core Processor","4GB DDR3L SDRAM Memory","More productive. Windows 10 is the best for bringing ideas forward and getting things done.","500GB Hard Drive, No Optical Drive","13.3'' diagonal FHD IPS WLED-backlit touch screen (1920x1080)"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('HP 15-ay013nr 15.6" Full-HD Laptop (6th Generation Core i5, 8GB RAM, 128GB SSD) with Windows 10', 3, 2, 3, 'https://images-na.ssl-images-amazon.com/images/I/416Gy2BkVqL._AC_US200_.jpg', 8, 1, 128, 2.5, 459.99, 'https://images-na.ssl-images-amazon.com/images/I/416Gy2BkVqL._AC_US500_.jpg', '{"Intel Core i5-6200U, 2.3GHz, Dual-Core Processor","8GB DDR3L SDRAM Memory","More productive. Windows 10 is the best for bringing ideas forward and getting things done.","128GB Solid-State Drive, No Optical Drive","13.3'' diagonal FHD IPS WLED-backlit touch screen (1920x1080)"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Microsoft Surface Pro 4 (128 GB, 4 GB RAM, Intel Core M)', 3, 4, 2, 'https://images-na.ssl-images-amazon.com/images/I/41yRDqilgHL._AC_US200_QL65_.jpg', 4, 1, 128, 4, 713.98, 'https://images-na.ssl-images-amazon.com/images/I/41yRDqilgHL._AC_US500_QL65_.jpg', '{"13.5-inch PixelSense touchscreen display (3000 x 2000) resolution","Windows 10 Pro operating system","Incredibly mobile at 3.48 pounds (1576 grams)","Surface Pen included","Please refer User Guide before use."}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('DELL XPS XPS9350-4007SLV 13.3-Inch Touchscreen (Intel Core i5 6200U 2.30 GHz Processor, 8 GB LPDDR3 RAM, 256 GB Hard Drive, Windows 10 Home), Machined Aluminum', 3, 2, 4, 'https://images-na.ssl-images-amazon.com/images/I/41+t2BscAjL._AC_US200_.jpg', 8, 1, 256, 4, 749.99, 'https://images-na.ssl-images-amazon.com/images/I/41+t2BscAjL._AC_US500_.jpg', '{"Intel Quad Core i7-6700HQ 2.6 GHz Processor; NVIDIA GeForce GTX 960M 4GB GDDR5","8 GB DDR3L SDRAM","1 TB HDD + 8 GB SSD Hybrid Drive Storage; Optical Drive Not included","15.6 Inch FHD (1920 x 1080 pixels) LED-lit Truelife Screen","Windows 10 Operating System; Matte Black featuring Red Chassis"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('HP Notebook 15-ay011nr 15.6-Inch Laptop (6th Gen Intel Core i5-6200U Processor, 8GB DDR3L SDRAM, 1TB HDD, Windows 10), Silver', 5, 2, 3, 'https://images-na.ssl-images-amazon.com/images/I/41Yv8ZhfQbL._AC_US200_.jpg', 8, 2, 1024, 1.8, 1499.99, 'https://images-na.ssl-images-amazon.com/images/I/41Yv8ZhfQbL._AC_US500_.jpg', '{"Intel Core i5-6200U, 2.3GHz, Dual-Core Processor","8GB DDR3L SDRAM Memory","More productive. Windows 10 is the best for bringing ideas forward and getting things done.","128GB Solid-State Drive, No Optical Drive","13.3'' diagonal FHD IPS WLED-backlit touch screen (1920x1080)"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS ROG GL752VW-DH71 17.3-inch Gaming Laptop (Intel i7 2.6GHz, 64GB DDR4 RAM, 1TB HDD, GTX960M 2GB Graphic Card, Windows 10)', 3, 1, 5, 'https://images-na.ssl-images-amazon.com/images/I/41TRuOp12iL._AC_US200_.jpg', 64, 2, 1024, 3, 1499.99, 'https://images-na.ssl-images-amazon.com/images/I/41TRuOp12iL._AC_US500_.jpg', '{"Powerful 6th-generation Intel Core i7-6500U 2.5GHz (Turbo up to 3.1GHz). Skylake","15.6 inches Matte FHD display. 1920 by 1080 resolution. Windows 10 Operating System.","NVIDIA GeForce GTX 960M gaming graphic card; 8GB RAM; 512GB SSD Storage. Backlit keyboard.","Gigabit Dual-Band 802.11AC ultra-fast Wi-Fi.","2x USB 2.0, 2x USB 3.0, 1x Headphone-out & Audio-in Combo Jack, 1x RJ45 LAN Jack for LAN insert, 1x HDMI, 1x Card Reader"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Dell Inspiron i7559-2512BLK 15.6 Inch FHD Laptop (6th Generation Intel Core i7, 8 GB RAM, 1 TB HDD + 8 GB SSD) NVIDIA GeForce GTX 960M', 3, 1, 4, 'https://images-na.ssl-images-amazon.com/images/I/419DWJfUXuL._AC_US200_.jpg', 8, 1, 1024, 2.4, 699.99, 'https://images-na.ssl-images-amazon.com/images/I/419DWJfUXuL._AC_US500_.jpg', '{"Intel Quad Core i7-6700HQ 2.6 GHz Processor; NVIDIA GeForce GTX 960M 4GB GDDR5","8 GB DDR3L SDRAM","1 TB HDD + 8 GB SSD Hybrid Drive Storage; Optical Drive Not included","15.6 Inch FHD (1920 x 1080 pixels) LED-lit Truelife Screen","Windows 10 Operating System; Matte Black featuring Red Chassis"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('HP Pavilion 15 15.6-Inch Laptop (AMD Quad-Core A6-5200 , 4GB RAM, 500GB HDD, DVD+/-RW, Webcam, Wifi, HDMI,Windows 10),Black', 4, 5, 3, 'https://images-na.ssl-images-amazon.com/images/I/410+Qjg+TfL._AC_US200_.jpg', 4, 2, 500, 0.8, 287.99, 'https://images-na.ssl-images-amazon.com/images/I/410+Qjg+TfL._AC_US500_.jpg', '{"2.0GHz AMD Quad-Core A6-5200 APU (2MB L2 Cache), AMD Radeon R4 graphics with up to 2048MB total graphics memory","4GB DDR3 SDRAM (1 DIMM) Memory, 500GB 5400RPM hard drive, SuperMulti DVD Burner","15.6-inch diagonal HD BrightView WLED-backlit display (1366x768)","802.11b/g/n WLAN, Integrated 10/100 BASE-T Ethernet LAN, HD Webcam, Multi-Format Digital Media Card Reader, 1 SuperSpeed USB 3.0, 2USB 2.0, HDMI, RJ-45, Headphone, Microphone, DTS Studio Sound with dual speakers, Full-size keyboard with numeric keypad, Front facing VGA Webcam with integrated digital microphone","Windows 10 Home 64 Bit, 3-cell 31WHr 2.8Ah lithium-ion polymer battery, Black"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS ZenBook UX303UA 13.3-Inch FHD Touchscreen Laptop, Intel Core i5, 8 GB RAM, 256 GB SSD, Windows 10 (64 bit)', 3, 2, 5, 'https://images-na.ssl-images-amazon.com/images/I/41+Ke3rTWGL._AC_US200_.jpg', 8, 1, 256, 2.3, 287.99, 'https://images-na.ssl-images-amazon.com/images/I/41+Ke3rTWGL._AC_US500_.jpg', '{"15.6'' Touch IPS 4K Ultra­-HD display, 3840 x 2160 resolution","Powerful Intel Skylake Core i7­-6700HQ 2.6 GHz Quad­core CPU (turbo to 3.5GHz). Nvidia GTX960M GPU","512GB SSD with transfer speeds of 1400MB/s and 16GB DDR4 RAM","1x Thunderbolt III (via USB Type­C), 1x Gen 2 USB 3.1 Type­C, 3x USB 3.0, 1x HDMI.Bluetooth 4.0, SDXC reader, 802.11ac Wi­Fi","Windows 10 (64 bit) Signature Edition. 1 ­year International Warranty with 1­ year Accidental Damage Protection."}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Toshiba CB35-B3340 13.3 Inch Chromebook (Intel Celeron, 4GB, 16GB SSD, Silver) Full HD-Screen', 2, 4, 9, 'https://images-na.ssl-images-amazon.com/images/I/41SJTSRFTRL._AC_US200_.jpg', 4, 1, 16, 2.4, 249.99, 'https://images-na.ssl-images-amazon.com/images/I/41SJTSRFTRL._AC_US500_.jpg', '{"Intel Celeron N3160 Quad-Core Processor 1.6GHz (Up to 2.24GHz)","100% Aluminum Chassis","4GB LPDDR3 Onboard SDRAM Memory, 32GB Internal Storage","14'' Full HD IPS Display (1920 x 1080), Intel HD Graphics","Google Chrome, Up to 12-hours Battery Life"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Asus F555LA-AB31 15.6-Inch Laptop (2.1 GHz Core i3-5010U Processor,4 GB RAM,500 GB Hard Drive, Windows 10), Black', 3, 3, 5, 'https://images-na.ssl-images-amazon.com/images/I/41uXvMCE9UL._AC_US200_.jpg', 4, 2, 500, 3.4, 699.99, 'https://images-na.ssl-images-amazon.com/images/I/41uXvMCE9UL._AC_US500_.jpg', '{"15.6'' display HD resolution.","5th Gen Intel CoreTM i3-5020U processor Smart dual-core, four-way processing performance for HD-quality computing","4GB system memory for basic multitasking","1TB hard drive for ample file storage space","Windows 10 Home"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('Samsung Series 9 NP900X3D-A04US 13.3-Inch Premium Ultrabook (Silver)', 3, 2, 7, 'https://images-na.ssl-images-amazon.com/images/I/51iRtMTpNAL._AC_US200_.jpg', 4, 1, 128, 3.5, 999.99, 'https://images-na.ssl-images-amazon.com/images/I/81VuNkZI79L._SX500_.jpg', '{"Intel Core i5-3317U Processor (1.7 GHz)","4 GB DDR3 RAM","128 GB Solid-State Drive","13.3-Inch Screen, Intel HD Graphics 4000","Windows 8 (64-bit)"}');
--statement-- 
INSERT INTO laptops (name, os_id, processor_id, brand_id, img, ram, storage_type_id, storage, rating, price, img_big, description)
  VALUES ('ASUS K501UW-AB78 15.6-inch Full-HD Gaming Laptop (Intel Core i7, GTX 960M, 8GB DDR4, 512GB SSD) Glacier Grey', 4, 1, 5, 'https://images-na.ssl-images-amazon.com/images/I/416Gy2BkVqL._AC_US200_.jpg', 8, 1, 512, 3.4, 879, 'https://images-na.ssl-images-amazon.com/images/I/416Gy2BkVqL._AC_US500_.jpg', '{"Powerful 6th-generation Intel Core i7-6500U 2.5GHz (Turbo up to 3.1GHz). Skylake","15.6 inches Matte FHD display. 1920 by 1080 resolution. Windows 10 Operating System.","NVIDIA GeForce GTX 960M gaming graphic card; 8GB RAM; 512GB SSD Storage. Backlit keyboard.","Gigabit Dual-Band 802.11AC ultra-fast Wi-Fi.","2x USB 2.0, 2x USB 3.0, 1x Headphone-out & Audio-in Combo Jack, 1x RJ45 LAN Jack for LAN insert, 1x HDMI, 1x Card Reader"}');
