CREATE TABLE laptops(
   id                                                                                              INTEGER  NOT NULL PRIMARY KEY 
  ,quan_in_stock                                                                                              INTEGER  NOT NULL
  ,prod_category                                                                                              VARCHAR(100) NOT NULL
  ,prod_name                                                                                                  VARCHAR(200) NOT NULL
  ,prod_img                                                                                                   VARCHAR(100) NOT NULL
  ,prod_rating                                                                                                INTEGER  NOT NULL
  ,prod_is_prime                                                                                              VARCHAR(1) NOT NULL
);


CREATE TABLE operating_systems
(
  id serial PRIMARY KEY,
  os_name INTEGER,
  processor VARCHAR(40),
  ram INTEGER,
  
)








INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1001,30,'Tradional Laptop','HP Notebook 15-ay011nr 15.6-Inch Laptop (6th Gen Intel Core i5-6200U Processor, 8GB DDR3L SDRAM, 1TB HDD, Windows 10), Silver','https://images-na.ssl-images-amazon.com/images/I/41AerRC5u6L._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1002,30,'Tradional Laptop','Asus F555LA-AB31 15.6-Inch Laptop (2.1 GHz Core i3-5010U Processor,4 GB RAM,500 GB Hard Drive, Windows 10), Black','https://images-na.ssl-images-amazon.com/images/I/41MW-Z2bY6L._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1003,30,'Tradional Laptop','Asus F555LA-AB31 15.6-Inch Laptop (2.1 GHz Core i3-5010U Processor,4 GB RAM,500 GB Hard Drive, Windows 10), Black','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1004,30,'Tradional Laptop','Dell Inspiron i7559-2512BLK 15.6 Inch FHD Laptop (6th Generation Intel Core i7, 8 GB RAM, 1 TB HDD + 8 GB SSD) NVIDIA GeForce GTX 960M','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1005,30,'Tradional Laptop','ASUS F556UA-AS54 15.6-inch Full-HD Laptop (Core i5, 8GB RAM, 256GB SSD) with Windows 10, Icicle Gold','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1006,30,'Tradional Laptop','Dell 15.6-Inch Gaming Laptop (6th Gen Intel Quad-Core i5-6300HQ Processor up to 3.2GHz, 8GB DDR3, 256GB SSD, Nvidia GeForce GTX 960M, Windows 10)','https://images-na.ssl-images-amazon.com/images/I/41XXZn8RfiL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1007,30,'Tradional Laptop','HP 15-ay013nr 15.6" Full-HD Laptop (6th Generation Core i5, 8GB RAM, 128GB SSD) with Windows 10','https://images-na.ssl-images-amazon.com/images/I/416Gy2BkVqL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1008,30,'Tradional Laptop','ASUS K501UW-AB78 15.6-inch Full-HD Gaming Laptop (Intel Core i7, GTX 960M, 8GB DDR4, 512GB SSD) Glacier Grey','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1009,30,'Tradional Laptop','ASUS ZenBook UX305UA 13.3-Inch Laptop (6th Generation Intel Core i5, 8GB RAM, 256 GB SSD, Windows 10), Titanium Gold','https://images-na.ssl-images-amazon.com/images/I/41Yv8ZhfQbL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1010,30,'Tradional Laptop','Acer Chromebook CB3-131-C3SZ 11.6-Inch Laptop (Intel Celeron N2840 Dual-Core Processor,2 GB RAM,16 GB Solid State Drive,Chrome), White','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1011,30,'Tradional Laptop','Apple MMGF2LL/A MacBook Air 13.3-Inch Laptop (128 GB) NEWEST VERSION','https://images-na.ssl-images-amazon.com/images/I/41AerRC5u6L._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1012,30,'Tradional Laptop','HP - 15.6" Laptop / AMD A6-Series / 4GB Memory / 500GB Hard Drive / DVDRW/CD-RW / Windows 10 - Black','https://images-na.ssl-images-amazon.com/images/I/416uktsoFOL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1013,30,'Tradional Laptop','Acer Chromebook 14, Aluminum, 14-inch Full HD, Intel Celeron Quad-Core N3160, 4GB LPDDR3, 32GB, Chrome, CB3-431-C5FM','https://images-na.ssl-images-amazon.com/images/I/518PvURfFsL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1014,30,'Tradional Laptop','Acer Aspire E 15, 15.6 Full HD, Intel Core i7, NVIDIA 940MX, 8GB DDR4, 256GB SSD, Windows 10 Home, E5-575G-76YK','https://images-na.ssl-images-amazon.com/images/I/41BrD2bCAeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1015,30,'Tradional Laptop','Apple MacBook Pro MF839LL/A 13.3-Inch Laptop with Retina Display (2.7 GHz Intel Core i5 Processor, 8 GB RAM, 128 GB Hard Drive, OS X El Capitan)','https://images-na.ssl-images-amazon.com/images/I/51nHbuhKnqL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1016,30,'Tradional Laptop','ASUS VivoBook E403SA-US21 14-inch Full HD Laptop (Intel Quad-Core N3700 Processor, 4 GB DDR3 RAM, 128GB eMMC Storage, Windows 10 Home OS) Metallic Gray','https://images-na.ssl-images-amazon.com/images/I/51Ip+mFaQTL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1017,30,'Tradional Laptop','HP Pavilion 15 15.6-Inch Laptop (AMD Quad-Core A6-5200 , 4GB RAM, 500GB HDD, DVD+/-RW, Webcam, Wifi, HDMI,Windows 10),Black','https://images-na.ssl-images-amazon.com/images/I/41AerRC5u6L._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1018,30,'Tradional Laptop','Asus X540LA-SI30205P 15.6-Inch Laptop (Intel Core i3, 4GB Memory,1TB Hard Drive, Windows 10 Home), Silver','https://images-na.ssl-images-amazon.com/images/I/51J1ndMEUQL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1019,30,'Tradional Laptop','Apple Macbook Pro MJLQ2LL/A 15-inch Laptop (2.2 GHz Intel Core i7 Processor, 16GB RAM, 256 GB Hard Drive, Mac OS X)','https://images-na.ssl-images-amazon.com/images/I/41nOwxSNxpL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1020,30,'Tradional Laptop','New Apple MMGF2LL/A MacBook Air 13.3-Inch Laptop (8GB RAM 128 GB SSD) MMGF2 NEWEST VERSION','https://images-na.ssl-images-amazon.com/images/I/516KpKhNFPL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1021,30,'Tradional Laptop','Apple MMGG2LL/A MacBook Air 13.3-Inch Laptop (Intel Core i5, 8GB, 256GB,Mac OS X), Silver','https://images-na.ssl-images-amazon.com/images/I/4112yZZu8PL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1022,30,'Tradional Laptop','ASUS ROG GL752VW-DH71 17.3-inch Gaming Laptop (Intel i7 2.6GHz, 16GB DDR4 RAM, 1TB HDD, GTX960M 2GB Graphic Card, Windows 10)','https://images-na.ssl-images-amazon.com/images/I/41TRuOp12iL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1023,30,'Tradional Laptop','Apple MacBook Pro MJLT2LL/A 15.4-Inch Laptop with Retina Display (512 GB)','https://images-na.ssl-images-amazon.com/images/I/41nUlN0d90L._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1024,30,'Tradional Laptop','ASUS C201 11.6 Inch Chromebook (Rockchip, 4 GB, 16GB SSD, Navy Blue)','https://images-na.ssl-images-amazon.com/images/I/41yFEX+AEQL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1025,30,'Tradional Laptop','ASUS ROG GL752VW-DH74 17-Inch Gaming Laptop, Discrete GPU GeForce GTX 960M 4 GB VRAM, 16GB DDR4, 1 TB, 128 GB SSD (ROG Metallic)','https://images-na.ssl-images-amazon.com/images/I/41TRuOp12iL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1026,30,'Tradional Laptop','ASUS ZenBook Pro UX501VW 15" 4K Touchscreen Laptop (Core i7-6700HQ CPU, 16 GB DDR4, 512 GB NVMe SSD, GTX960M GPU, Thunderbolt III, Win 10 Cortana Premium)','https://images-na.ssl-images-amazon.com/images/I/41oX-+X+HIL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1027,30,'Tradional Laptop','ASUS C200MA Chromebook 11.6 Inch, Intel Dual Core, 4GB RAM, 16G EMMC + TPM (Black)','https://images-na.ssl-images-amazon.com/images/I/41FNGl9uX1L._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1028,30,'Tradional Laptop','Acer Chromebook 15 CB5-571-C1DZ (15.6-Inch Full HD IPS, 4GB RAM, 16GB SSD)','https://images-na.ssl-images-amazon.com/images/I/5165f4fk49L._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1029,30,'Tradional Laptop','Apple MacBook Pro MF840LL/A 13.3-Inch Laptop with Retina Display (256 GB, 2.7 GHz dual-core Intel Core i5 processor, 8 GB 1866 MHz LPDDR3 RAM), Silver','https://images-na.ssl-images-amazon.com/images/I/51nHbuhKnqL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1030,30,'Tradional Laptop','2016 Newest Dell Inspiron 5000 Touchscreen 15.6" FHD Laptop, 6th Intel Core i5-6200U up to 2.8GHz, 8 GB RAM, 1 TB HDD, DVD, Backlit keyboard, HDMI, Bluetooth, 802.11ac, RealSense 3D Webcam, Windows 10','https://images-na.ssl-images-amazon.com/images/I/41TEYABuTVL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1031,30,'Tradional Laptop','ASUS ZenBook UX303UB 13.3-Inch QHD+ Touchscreen Laptop, Intel Core i7, 12 GB RAM, 512 GB SSD, Discrete GPU Nvidia GT940M, Windows 10 (64 bit)','https://images-na.ssl-images-amazon.com/images/I/41+Ke3rTWGL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1032,30,'Tradional Laptop','HP Pavilion 13-s128nr x360 13.3-Inch Full-HD 2-in-1 Laptop (Core i5, 8GB RAM, 128GB SSD) with Windows 10','https://images-na.ssl-images-amazon.com/images/I/41AuBloBZSL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1033,30,'Tradional Laptop','ASUS ZenBook Flip UX360CA-DBM1T 13.3-inch Touchscreen Laptop (Intel Core M CPU, 8 GB RAM, 512 GB Solid State Drive, Windows 10)','https://images-na.ssl-images-amazon.com/images/I/31-49dCBMwL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1034,30,'Tradional Laptop','Samsung Chromebook 3 XE500C13-K02US 4 GB RAM 11.6" Laptop (Black)','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1035,30,'Tradional Laptop','ASUS ROG GL552VW-DH74 15-Inch Gaming Laptop, Discrete GPU GeForce GTX 960M 4GB VRAM, 16GB DDR4, 1TB, 128GB SSD (ROG Metallic)','https://images-na.ssl-images-amazon.com/images/I/41rzZTFQqWL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1036,30,'Tradional Laptop','ASUS ROG GL552VW-DH71 15-Inch Gaming Laptop, Discrete GPU GeForce GTX 960M 2GB VRAM, 16GB DDR4, 1TB (ROG Metallic)','https://images-na.ssl-images-amazon.com/images/I/51rDLb7i7RL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1037,30,'Tradional Laptop','ASUS F555UA-EH71 15.6 Inch, Intel Core i7, 8GB, 1TB HDD Laptop, Windows 10 (64bit)','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1038,30,'Tradional Laptop','ASUS K501UX 15.6-inch Gaming Laptop (Intel Core i7 Processor, 8GB RAM, 256GB SSD Hard Drive, Windows 10 (64 bit)), Black/Silver Metal','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1039,30,'Tradional Laptop','Apple 13-inch MacBook Pro (Intel Dual Core i5 2.5GHz, 4GB RAM, 500GB HDD, HD Graphics 4000, OS X Lion)','https://images-na.ssl-images-amazon.com/images/I/41vZl7Pe2HL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1040,30,'Tradional Laptop','Microsoft Surface Book (512 GB, 16 GB RAM, Intel Core i7, NVIDIA GeForce graphics)','https://images-na.ssl-images-amazon.com/images/I/419DWJfUXuL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1041,30,'Tradional Laptop','Apple MacBook Pro MF841LL/A 13.3-Inch Laptop with Retina Display (512 GB)','https://images-na.ssl-images-amazon.com/images/I/41uXvMCE9UL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1042,30,'Tradional Laptop','Toshiba CB35-B3340 13.3 Inch Chromebook (Intel Celeron, 4GB, 16GB SSD, Silver) Full HD-Screen','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1043,30,'Tradional Laptop','ASUS ZenBook UX303UA 13.3-Inch FHD Touchscreen Laptop, Intel Core i5, 8 GB RAM, 256 GB SSD, Windows 10 (64 bit)','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1044,30,'Tradional Laptop','Apple MacBook Air MJVM2LL/A 11.6-Inch laptop(1.6 GHz Intel i5, 128 GB SSD, Integrated Intel HD Graphics 6000, Mac OS X Yosemite)','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1045,30,'Tradional Laptop','Apple MacBook Air MJVM2LL/A 11.6-Inch laptop(1.6 GHz Intel i5, 128 GB SSD, Integrated Intel HD Graphics 6000, Mac OS X Yosemite)','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1046,30,'Tradional Laptop','Lenovo ideapad 300 80Q70021US 15.6-Inch Laptop (Intel Core i5 6200U, 8 GB RAM, 1TB HDD, Windows 10)','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1047,30,'Tradional Laptop','Dell Inspiron i7359-8404SLV 13.3 Inch 2-in-1 Touchscreen Laptop (6th Generation Intel Core i7, 8 GB RAM, 256 GB SSD)','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1048,30,'Tradional Laptop','HP 15-ay018nr 15.6-Inch Laptop (Intel Core i7, 8GB RAM, 256GB SSD)','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1049,30,'Tradional Laptop','HP Stream 13.3-Inch Laptop (Intel Celeron, 2 GB RAM, 32 GB SSD, Cobalt Blue) with Office 365 Personal for One Year','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1050,30,'Tradional Laptop','DELL XPS XPS9350-4007SLV 13.3-Inch Touchscreen (Intel Core i5 6200U 2.30 GHz Processor, 8 GB LPDDR3 RAM, 256 GB Hard Drive, Windows 10 Home), Machined Aluminum','https://images-na.ssl-images-amazon.com/images/I/lulXXyeL._AC_US200_.jpg',4,'Y');
INSERT INTO windows_laptops(win_laptop_id,quan_in_stock,prod_category,prod_name,prod_img,prod_rating,prod_is_prime) VALUES (1051,30,'Tradional Laptop','ASUS ROG G751JY-VS71(WX) 17-Inch Gaming Laptop, Nvidia GeForce GTX 980M , 16 GB RAM, 1 TB HDD (Win 10 Version)','https://images-na.ssl-images-amazon.com/images/I/41HfDkXXyeL._AC_US200_.jpg',4,'Y');